export const EXPERIENCE_SET_DATE_FILTER =
  "experience/EXPERIENCE_SET_DATE_FILTER";
export const EXPERIENCE_SET_BOOKINGS = "experience/EXPERIENCE_SET_BOOKINGS";
export const EXPERIENCE_SET_COMPLETED_BOOKINGS =
  "experience/EXPERIENCE_SET_COMPLETED_BOOKINGS";
